name: Build UMP

on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm32", "aarch64", "x86_64" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:
        
      - uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install mako meson ninja
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          envsubst <android-turnip-${{matrix.arch}} >build-crossfile-turnip
          meson setup "build-android-turnip" \
            --cross-file "build-crossfile-turnip" \
            -Dbuildtype=release \
            --prefix=/tmp/mesa \
            -Dplatforms=android \
            -Dplatform-sdk-version=33 \
            -Dandroid-stub=true \
            -Dgallium-drivers= \
            -Dvulkan-drivers=freedreno \
            -Dfreedreno-kmds=kgsl \
            -Dandroid-strict=false \
            -Db_lto=true
          ninja -C "build-android-turnip" install
          mkdir /tmp/mesa/toupload
          mv /tmp/mesa/lib/libOSMesa.so.8.0.0 /tmp/mesa/lib/libvulkan_freedreno.so /tmp/mesa/toupload/
          cd /tmp/mesa/toupload
          mv libOSMesa.so.8.0.0 libOSMesa.so
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: UMP_${{matrix.arch}}
          path: /tmp/mesa/toupload/libvulkan_freedreno.so
